[colors.primary]
background = "#24273A"
foreground = "#abb2bf"

[cursor]
thickness = 0.2

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true

[window]
startup_mode = "Fullscreen"
option_as_alt = "Both"
