[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.cursor]
cursor = "#82aaff"
text = "#282c35"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#282c35"
foreground = "#abb2bf"

[colors.selection]
background = "#fe5186"
text = "#282c35"

[cursor]
thickness = 1.0

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true

[window]
startup_mode = "Fullscreen"

[window.padding]
x = 0
y = 0
