[colors.primary]
background = "#24273A"
foreground = "#abb2bf"

[cursor]
thickness = 0.2

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Bold"

[font.offset]
x = 0
y = 1

[selection]
save_to_clipboard = true

[window]
padding = {x = 0, y = 0}
startup_mode = "SimpleFullscreen"
option_as_alt = "Both"
decorations = "None"
opacity = 0.9999
